//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Backend {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Backend() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NailShop.Resources.Backend", typeof(Backend).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nail Shop Online.
        /// </summary>
        public static string backendName {
            get {
                return ResourceManager.GetString("backendName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Photo.
        /// </summary>
        public static string btnAddPhoto {
            get {
                return ResourceManager.GetString("btnAddPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string btnClose {
            get {
                return ResourceManager.GetString("btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string btnOk {
            get {
                return ResourceManager.GetString("btnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string btnSignIn {
            get {
                return ResourceManager.GetString("btnSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Store.
        /// </summary>
        public static string chooseStore {
            get {
                return ResourceManager.GetString("chooseStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT US.
        /// </summary>
        public static string headAbout {
            get {
                return ResourceManager.GetString("headAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALBUMS LIST.
        /// </summary>
        public static string headAlbumsList {
            get {
                return ResourceManager.GetString("headAlbumsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BRAND LIST.
        /// </summary>
        public static string headBrand {
            get {
                return ResourceManager.GetString("headBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create/View Brand.
        /// </summary>
        public static string headCreateBrand {
            get {
                return ResourceManager.GetString("headCreateBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create/View Photo.
        /// </summary>
        public static string headCreatePhoto {
            get {
                return ResourceManager.GetString("headCreatePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create/View Product Hot.
        /// </summary>
        public static string headCreateProductHot {
            get {
                return ResourceManager.GetString("headCreateProductHot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create/View Promotion.
        /// </summary>
        public static string headCreatePromotion {
            get {
                return ResourceManager.GetString("headCreatePromotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create/View Promotion Category.
        /// </summary>
        public static string headCreatePromotionCategory {
            get {
                return ResourceManager.GetString("headCreatePromotionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create/View Slide.
        /// </summary>
        public static string headCreateSlider {
            get {
                return ResourceManager.GetString("headCreateSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create/View Video.
        /// </summary>
        public static string headCreateVideo {
            get {
                return ResourceManager.GetString("headCreateVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order List.
        /// </summary>
        public static string headOrderList {
            get {
                return ResourceManager.GetString("headOrderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRODUCT HOT.
        /// </summary>
        public static string headProductHot {
            get {
                return ResourceManager.GetString("headProductHot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion Category List.
        /// </summary>
        public static string headPromotionCategoryList {
            get {
                return ResourceManager.GetString("headPromotionCategoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion List.
        /// </summary>
        public static string headPromotionList {
            get {
                return ResourceManager.GetString("headPromotionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLIDER.
        /// </summary>
        public static string headSlide {
            get {
                return ResourceManager.GetString("headSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIDEO LIST.
        /// </summary>
        public static string headVideoList {
            get {
                return ResourceManager.GetString("headVideoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string headWelcome {
            get {
                return ResourceManager.GetString("headWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string lblActive {
            get {
                return ResourceManager.GetString("lblActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Url.
        /// </summary>
        public static string lblBrandUrl {
            get {
                return ResourceManager.GetString("lblBrandUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string lblCity {
            get {
                return ResourceManager.GetString("lblCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string lblCode {
            get {
                return ResourceManager.GetString("lblCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string lblDescription {
            get {
                return ResourceManager.GetString("lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Percent(%).
        /// </summary>
        public static string lblDiscountPercent {
            get {
                return ResourceManager.GetString("lblDiscountPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        public static string lblFromDate {
            get {
                return ResourceManager.GetString("lblFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string lblImage {
            get {
                return ResourceManager.GetString("lblImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image cover.
        /// </summary>
        public static string lblImageCover {
            get {
                return ResourceManager.GetString("lblImageCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image photo.
        /// </summary>
        public static string lblImagePhoto {
            get {
                return ResourceManager.GetString("lblImagePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Description.
        /// </summary>
        public static string lblLongDescription {
            get {
                return ResourceManager.GetString("lblLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string lblPrice {
            get {
                return ResourceManager.GetString("lblPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string lblPriority {
            get {
                return ResourceManager.GetString("lblPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string lblProductName {
            get {
                return ResourceManager.GetString("lblProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion Name.
        /// </summary>
        public static string lblPromotionName {
            get {
                return ResourceManager.GetString("lblPromotionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string lblQuantity {
            get {
                return ResourceManager.GetString("lblQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Description.
        /// </summary>
        public static string lblShortDescription {
            get {
                return ResourceManager.GetString("lblShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sing In.
        /// </summary>
        public static string lblSignIn {
            get {
                return ResourceManager.GetString("lblSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string lblState {
            get {
                return ResourceManager.GetString("lblState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        public static string lblToDate {
            get {
                return ResourceManager.GetString("lblToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url link.
        /// </summary>
        public static string lblUrlLink {
            get {
                return ResourceManager.GetString("lblUrlLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email/Login Name.
        /// </summary>
        public static string lblUserName {
            get {
                return ResourceManager.GetString("lblUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string lblVideo {
            get {
                return ResourceManager.GetString("lblVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZipCode.
        /// </summary>
        public static string lblZipCode {
            get {
                return ResourceManager.GetString("lblZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete?.
        /// </summary>
        public static string messDelete {
            get {
                return ResourceManager.GetString("messDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Detail.
        /// </summary>
        public static string messPhotoDetail {
            get {
                return ResourceManager.GetString("messPhotoDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You save sucessfull!.
        /// </summary>
        public static string mesSuccess {
            get {
                return ResourceManager.GetString("mesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warring.
        /// </summary>
        public static string mesTitleWarring {
            get {
                return ResourceManager.GetString("mesTitleWarring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string pldPassword {
            get {
                return ResourceManager.GetString("pldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search product.
        /// </summary>
        public static string pldSearchProduct {
            get {
                return ResourceManager.GetString("pldSearchProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email/Login Name.
        /// </summary>
        public static string pldUserName {
            get {
                return ResourceManager.GetString("pldUserName", resourceCulture);
            }
        }
    }
}
