//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FormTitle {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormTitle() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NailShop.Resources.FormTitle", typeof(FormTitle).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abouts - ATSoft Inc | Nail POS Systems.
        /// </summary>
        public static string formAbout {
            get {
                return ResourceManager.GetString("formAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact - ATSoft Inc | Nail POS Systems.
        /// </summary>
        public static string formContact {
            get {
                return ResourceManager.GetString("formContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery - ATSoft Inc | Nail POS Systems.
        /// </summary>
        public static string formGallery {
            get {
                return ResourceManager.GetString("formGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home - ATSoft Inc | Nail POS Systems.
        /// </summary>
        public static string formHome {
            get {
                return ResourceManager.GetString("formHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order - ATSoft Inc | Nail POS Systems.
        /// </summary>
        public static string formOrder {
            get {
                return ResourceManager.GetString("formOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order - ATSoft Inc | Nail POS Systems.
        /// </summary>
        public static string formOrderCreate {
            get {
                return ResourceManager.GetString("formOrderCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video - ATSoft Inc | Nail POS Systems.
        /// </summary>
        public static string formVideo {
            get {
                return ResourceManager.GetString("formVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abouts ATSoft Inc, Nail POS Systems.
        /// </summary>
        public static string titleAbouts {
            get {
                return ResourceManager.GetString("titleAbouts", resourceCulture);
            }
        }
    }
}
