//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NailShop.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public long CategoryID { get; set; }
        public int LocalID { get; set; }
        public long StoreID { get; set; }
        public string Code { get; set; }
        public string CategoryName { get; set; }
    }
}
