//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NailShop.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public Language()
        {
            this.NewsLangs = new HashSet<NewsLang>();
        }
    
        public string LangID { get; set; }
        public string Language1 { get; set; }
    
        public virtual ICollection<NewsLang> NewsLangs { get; set; }
    }
}
