//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NailShop.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoDetail
    {
        public PhotoDetail()
        {
            this.PhotoDetailLangs = new HashSet<PhotoDetailLang>();
        }
    
        public long DetailID { get; set; }
        public long PhotoID { get; set; }
        public int Sort { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Photo Photo { get; set; }
        public virtual ICollection<PhotoDetailLang> PhotoDetailLangs { get; set; }
    }
}
