//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NailShop.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public Photo()
        {
            this.PhotoDetails = new HashSet<PhotoDetail>();
            this.PhotoLangs = new HashSet<PhotoLang>();
        }
    
        public long ID { get; set; }
        public bool IsPhoto { get; set; }
        public int Sort { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<PhotoDetail> PhotoDetails { get; set; }
        public virtual ICollection<PhotoLang> PhotoLangs { get; set; }
    }
}
