//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NailShop.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefNo
    {
        public string RefType { get; set; }
        public int StoreID { get; set; }
        public string FormatString { get; set; }
        public int Length { get; set; }
        public long CurrNumber { get; set; }
        public string Description { get; set; }
    }
}
