//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NailShop.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SynCustomer
    {
        public long CustomerID { get; set; }
        public Nullable<bool> Active { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public string BarCode { get; set; }
        public string FullName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string AddressAddr1 { get; set; }
        public string AddressAddr2 { get; set; }
        public string AddressAddr3 { get; set; }
        public string AddressAddr4 { get; set; }
        public string AddressAddr5 { get; set; }
        public string AddressAddr1S { get; set; }
        public string AddressAddr2S { get; set; }
        public string AddressAddr3S { get; set; }
        public string AddressAddr4S { get; set; }
        public string AddressAddr5S { get; set; }
        public Nullable<bool> International { get; set; }
        public string Country { get; set; }
        public string HomePhone { get; set; }
        public string CellPhone { get; set; }
        public string Notes { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public Nullable<int> PriceLevel { get; set; }
        public Nullable<decimal> TotalSpend { get; set; }
        public Nullable<System.DateTime> CustSince { get; set; }
        public Nullable<System.DateTime> LastVisit { get; set; }
        public Nullable<int> NumVisit { get; set; }
        public int RecordState { get; set; }
    }
}
