//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NailShop.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SynInvoice
    {
        public long InvoiceID { get; set; }
        public int StoreID { get; set; }
        public int LocalID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<bool> IsPending { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string InvoiceNo { get; set; }
        public string BusinessName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string AddressAddr1 { get; set; }
        public string AddressAddr2 { get; set; }
        public string AddressAddr3 { get; set; }
        public string AddressAddr4 { get; set; }
        public string AddressAddr5 { get; set; }
        public string AddressAddr1S { get; set; }
        public string AddressAddr2S { get; set; }
        public string AddressAddr3S { get; set; }
        public string AddressAddr4S { get; set; }
        public string AddressAddr5S { get; set; }
        public Nullable<bool> SkipTax { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> SaleTax { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public Nullable<decimal> AmtPaid { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> AmtCredit { get; set; }
        public Nullable<decimal> Shipping { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<bool> Voided { get; set; }
        public string Notes { get; set; }
        public string Memo { get; set; }
        public int RecordState { get; set; }
        public int InvoiceStatus { get; set; }
    }
}
