//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NailShop.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SynProduct
    {
        public int ProductID { get; set; }
        public string BarCode { get; set; }
        public string ProdNo { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Price1 { get; set; }
        public Nullable<decimal> Price2 { get; set; }
        public Nullable<decimal> Price3 { get; set; }
        public Nullable<int> ProdType { get; set; }
        public string ProductUrl { get; set; }
        public Nullable<int> UnitsInStock { get; set; }
        public Nullable<bool> InItem { get; set; }
        public Nullable<bool> NoTax { get; set; }
        public string EditSequence { get; set; }
        public int RecordState { get; set; }
        public bool IsHost { get; set; }
    }
}
